components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Route:
      properties:
        distance:
          title: Distance
          type: integer
        points:
          items:
            type: integer
          title: Points
          type: array
      required:
      - distance
      - points
      title: Route
      type: object
    RouteResponse:
      properties:
        route:
          $ref: '#/components/schemas/Route'
      title: RouteResponse
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /route/{from_id}/{to_id}:
    get:
      operationId: makeRoute
      parameters:
      - in: path
        name: from_id
        required: true
        schema:
          title: From Id
          type: integer
      - in: path
        name: to_id
        required: true
        schema:
          title: To Id
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouteResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Make Route
